@echo off
REM
REM Create backup of our pbworks site using their web API.
REM NOTE: There's an API to get a list of files, but I'm 
REM too lazy to create a full JSON app for this, so you
REM need to update the list below before running.
REM
call getpage "Bubble Templates"
call getpage "ConflatePumsQueryWithTracts Phases"
call getpage "Coord Ref Systems"
call getpage "Csv2Kml Tool"
call getpage "CSV Metadata"
call getpage "CsvPlusMap Tool"
call getpage "Data File Reference"
call getpage "Digital Populations Tutorial"
call getpage "Dp2Kml Tool"
call getpage "FAQ"
call getpage "FrontPage"
call getpage "Glossary"
call getpage "How to Start Developing"
call getpage "Meeting Agenda"
call getpage "Placemark Template"
call getpage "Running Digital Populations"
call getpage "schema:dpfxml"
call getpage "schema:dprxml"
call getpage "schema: household rzns"
call getpage "schema: household rzns (pums)"
call getpage "schema: households sample"
call getpage "schema: landuse map"
call getpage "schema: parameters file"
call getpage "schema: population rzns"
call getpage "schema: population sample"
call getpage "schema: region map"
call getpage "schema: region table"
call getpage "SideBar"
call getpage "The Relationship File GUI"

call getfile "cerl.png"
call getfile "dpgui-households.png"
call getfile "dpgui-landuse.png"
call getfile "dpgui-population.png"
call getfile "dpgui-regions.png"
call getfile "dpgui-traits.png"
call getfile "Geographic map with regions.png"
call getfile "Map with plausible placement of households.png"
call getfile "Map with poor placement of households.png"
call getfile "Region map, rendered as a raster.png"
call getfile "ri_nlcd240.png"
call getfile "ri_tracts240.png"
