/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cerl.gui.forms;

import cerl.gui.standard.utilities.Result;
import cerl.gui.utilities.ConstraintMap;
import cerl.gui.utilities.DigPopGUIInformation;
import cerl.gui.utilities.DigPopGUIUtilityClass;
import cerl.gui.utilities.Forbid;
import cerl.gui.utilities.HelpFileScreenNames;

/**
 *
 * @author ajohnson
 */
public class ConstraintMapDetails extends javax.swing.JFrame {

    private final String SCREEN_NAME = HelpFileScreenNames.STEP_TWO_HELP_FILE_NAME.toString();
    private ConstraintMap constraintMap = new ConstraintMap();
    private boolean isEditing = false;
    private DigPopGUIInformation digPopGUIInformation;

    public ConstraintMapDetails(
            DigPopGUIInformation digPopGUIInformation,
            ConstraintMap constraintMap) {
        this.digPopGUIInformation = digPopGUIInformation;
        this.constraintMap = constraintMap;

        initComponents();
        
        Forbid currentForbid = this.constraintMap.getForbid();
        if (currentForbid.equals(new Forbid())) {
            this.isEditing = false;
        } else {
            this.isEditing = true;
            loadDetails(currentForbid);
        }

        this.txtConstraintMap.setText(constraintMap.getFilePath());

        pack();
    }

    private void loadDetails(Forbid currentForbid) {
        this.txtConstraintMapDescription.setText(currentForbid.getDesc());
        this.txtConstraintMapMapSelect.setText(currentForbid.getMapSelect());
        this.txtConstraintMapPumsTraitField.setText(currentForbid.getPumsTraitField());
        this.txtConstraintMapPumsTraitTable.setText(currentForbid.getPumsTraitTable());
        this.txtConstraintMapPumsTraitSelect.setText(currentForbid.getPumsTraitSelect());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtConstraintMap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtConstraintMapDescription = new javax.swing.JTextField();
        txtConstraintMapMapSelect = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtConstraintMapPumsTraitTable = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtConstraintMapPumsTraitField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtConstraintMapPumsTraitSelect = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuHelp1 = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Constraint Map:");

        txtConstraintMap.setEditable(false);

        jLabel2.setText("Description:");

        jLabel3.setText("Map Select:");

        jLabel4.setText("Pums Trait Table:");

        jLabel5.setText("Pums Trait Field:");

        jLabel6.setText("Pums Trait Select:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Constraint Map Forbid Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConstraintMap))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConstraintMapDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConstraintMapMapSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConstraintMapPumsTraitTable, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConstraintMapPumsTraitField, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConstraintMapPumsTraitSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtConstraintMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtConstraintMapDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtConstraintMapMapSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtConstraintMapPumsTraitTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtConstraintMapPumsTraitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtConstraintMapPumsTraitSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenuHelp1.setText("Help");
        jMenuHelp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHelp1MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenuHelp1);

        jMenuAbout.setText("About");
        jMenuAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAboutMouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenuAbout);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuHelp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHelp1MouseClicked
        DigPopGUIUtilityClass.loadDefaultHelpGUIByScreenName(SCREEN_NAME);
    }//GEN-LAST:event_jMenuHelp1MouseClicked

    private void jMenuAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAboutMouseClicked
        new About().setVisible(true);
    }//GEN-LAST:event_jMenuAboutMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (isEditing) {
            Forbid currentForbid = this.constraintMap.getForbid();
            String desc = this.txtConstraintMapDescription.getText();
            String mapSelect = this.txtConstraintMapMapSelect.getText();
            String pumsTraitTable = this.txtConstraintMapPumsTraitTable.getText();
            String pumsTraitField = this.txtConstraintMapPumsTraitField.getText();
            String pumsTraitSelect = this.txtConstraintMapPumsTraitSelect.getText();

            currentForbid.setDesc(desc);
            currentForbid.setMapSelect(mapSelect);
            currentForbid.setPumsTraitField(pumsTraitField);
            currentForbid.setPumsTraitSelect(pumsTraitSelect);
            currentForbid.setPumsTraitTable(pumsTraitTable);
        } else {
            String desc = this.txtConstraintMapDescription.getText();
            String mapSelect = this.txtConstraintMapMapSelect.getText();
            String pumsTraitTable = this.txtConstraintMapPumsTraitTable.getText();
            String pumsTraitField = this.txtConstraintMapPumsTraitField.getText();
            String pumsTraitSelect = this.txtConstraintMapPumsTraitSelect.getText();

            this.constraintMap.addNewForbid(
                    desc,
                    mapSelect,
                    pumsTraitTable,
                    pumsTraitField,
                    pumsTraitSelect);
        }
        
        saveToFile();
        
        openStepTwo();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        openStepTwo();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * Saves the information to the DigPop object
     */
    private void saveToFile() {
        //Save to file
        Result result = DigPopGUIUtilityClass.saveDigPopGUIInformationSaveFile(
                this.digPopGUIInformation,
                this.digPopGUIInformation.getFilePath());
    }
    
    private void openStepTwo(){
        StepTwo stepTwo = new StepTwo(this.digPopGUIInformation);
        stepTwo.setVisible(true);
        stepTwo.setLocationRelativeTo(this);
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenu jMenuHelp1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtConstraintMap;
    private javax.swing.JTextField txtConstraintMapDescription;
    private javax.swing.JTextField txtConstraintMapMapSelect;
    private javax.swing.JTextField txtConstraintMapPumsTraitField;
    private javax.swing.JTextField txtConstraintMapPumsTraitSelect;
    private javax.swing.JTextField txtConstraintMapPumsTraitTable;
    // End of variables declaration//GEN-END:variables
}
