/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cerl.gui.forms;

import java.util.*;
import cerl.gui.standard.utilities.MarkovTableModel;
import cerl.gui.standard.utilities.customTableCellRenderer;
import cerl.gui.standard.utilities.jTableButtonMouseListener;
import cerl.gui.utilities.MarkovTableCell;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 * Allows the user to set up a new Markov Chain. 
 * Depends on the MarkovTableModel and MarkovTable Cell
 * @author mrivera
 */
public class MarkovChainMatrix extends javax.swing.JFrame {

    private final MarkovTableModel myTable;
            
    /**
     * Creates new form MarkovChainMatrix
     * 
     * TO DO: Pull from Survey/Census data files, Write out to CSV files
     */
    public MarkovChainMatrix() {
        ArrayList<String> columnNames = new ArrayList<>();
        columnNames.addAll(Arrays.asList("","Value","","","","Amount Left",""));

        //columns must be rows+1 because the header row is the -1th row.
        MarkovTableCell[][] cellValues = new MarkovTableCell[6][7];
        //MarkovTableCell(int row, int column, Object value, boolean calculated, boolean error, boolean editable)
        cellValues[0][0] = new MarkovTableCell(0, 0, "Value", false, false, false);
        cellValues[4][0] = new MarkovTableCell(4, 0, "Amount Left", false, false, false);
        cellValues[5][0] = new MarkovTableCell(5, 0, "", false, false, false);
        cellValues[0][1] = new MarkovTableCell(0, 1, "Proportion", false, false, false);
        cellValues[0][6] = new MarkovTableCell(5, 0, "", false, false, false);
                
        //proportions
        cellValues[0][2] = new MarkovTableCell(0, 2, 0.22, false, false, false);
        cellValues[0][3] = new MarkovTableCell(0, 3, 0.23, false, false, false);
        cellValues[0][4] = new MarkovTableCell(0, 4, 0.24, false, false, false);
        cellValues[1][1] = new MarkovTableCell(1, 1, 0.92, false, false, false);
        cellValues[2][1] = new MarkovTableCell(2, 1, 0.93, false, false, false);
        cellValues[3][1] = new MarkovTableCell(3, 1, 0.94, false, false, false);
        
        //create table with custom MarkovTableModel
        myTable = new MarkovTableModel(columnNames, cellValues);
       
        initComponents();
       
        //sets up columns with new renderer, and clear buttons for the rows/columns
        for(int i=0; i<columnNames.size(); i++){
            TableColumn tableCol = jTable_MarkovMatrix.getColumnModel().getColumn(i);
            tableCol.setCellRenderer(new customTableCellRenderer());
        }
        //adds the mouse listener for the buttons to work in the jTable
        jTable_MarkovMatrix.addMouseListener(new jTableButtonMouseListener(jTable_MarkovMatrix));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_MarkovMatrix = new javax.swing.JTable();
        jButton_Back = new javax.swing.JButton();
        jButton_Cancel = new javax.swing.JButton();
        jButton_Save = new javax.swing.JButton();
        jButton_Clear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(840, 500));

        jTextField1.setToolTipText("Please enter the name of the Markov Chain for saving and reuse later.");

        jLabel1.setText("Markov Chain Name:");

        jTable_MarkovMatrix.setModel(myTable);
        jTable_MarkovMatrix.setAlignmentY(0.0F);
        jTable_MarkovMatrix.setCellEditor(jTable_MarkovMatrix.getCellEditor());
        jTable_MarkovMatrix.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable_MarkovMatrix.setFillsViewportHeight(true);
        jTable_MarkovMatrix.setMinimumSize(new java.awt.Dimension(100, 300));
        jTable_MarkovMatrix.setName("Markov Chain Matrix"); // NOI18N
        jTable_MarkovMatrix.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_MarkovMatrix);
        jTable_MarkovMatrix.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton_Back.setText("Back to Definitions");
        jButton_Back.setToolTipText("Go back to the previous step");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        jButton_Cancel.setText("Cancel Creation of New Markov Chain Matrix");
        jButton_Cancel.setToolTipText("Cancel the creation of a new Markov Chain matrix");
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });

        jButton_Save.setText("Save New Markov Chain");
        jButton_Save.setToolTipText("Saves the current matrix as a new Markov Chain");

        jButton_Clear.setText("Clear All Inputs");
        jButton_Clear.setName("ClearButton"); // NOI18N
        jButton_Clear.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        jMenuBar1.setName("Markov Chain Matrix"); // NOI18N

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("Markov Chain Matrix");
        jMenuBar1.getAccessibleContext().setAccessibleDescription("Add a new Markov Chain Matrix");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jButton_Back)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Cancel)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Save))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Clear))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Back)
                    .addComponent(jButton_Cancel)
                    .addComponent(jButton_Save))
                .addContainerGap())
        );

        jButton_Clear.getAccessibleContext().setAccessibleDescription("Clear all user entered data from the table.");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sends the user back to the previous step
     * @param evt 
     */
    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_BackActionPerformed

    /**
     * Cancels creation of the current Markov chain.
     * @param evt 
     */
    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_CancelActionPerformed

    /**
     * Clears the data entered by the user
     * @param evt 
     */
    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        //Clear all user entered inputs from the grid.
        myTable.clear(1, 1, 2, 1);
    }//GEN-LAST:event_jButton_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarkovChainMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarkovChainMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarkovChainMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarkovChainMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
                        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarkovChainMatrix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_MarkovMatrix;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
