/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cerl.gui.forms;

import cerl.gui.utilities.DigPopGUIUtilityClass;
import cerl.gui.utilities.HelpFileScreenNames;
import cerl.gui.utilities.SurveyColumnGroupsTableItemModel;
import cerl.gui.utilities.SurveyColumnValue;
import cerl.gui.utilities.SurveyColumnValuesGrouping;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 * Allows a user to group Survey information
 * @author ajohnson
 */
public class SelectSurveyDataColumnGroupings extends javax.swing.JFrame {
    
    private final cerl.gui.utilities.Class selectSurveyClass;
    private JList allSurveyClassesList;
    private final SurveyColumnGroupsTableItemModel surveyColumnGroupsTableItemModel;
    private final StepThree parentStep;
    private ArrayList<SurveyColumnValuesGrouping> nonEditedSurveyColumnValuesGroupings = new ArrayList<>();
    private ArrayList<SurveyColumnValue> nonEditedSurveyColumnValues = new ArrayList<>();
    private final String SCREEN_NAME = HelpFileScreenNames.STEP_THREE_HELP_FILE_NAME.toString();
    
    /**
     * Creates new form SelectSurveyDataColumnGroupings
     * @param selectSurveyClass - The Utility Class of the current Survey data
     * @param parentStep - The instance of Step Three this is associated with
     */
    public SelectSurveyDataColumnGroupings(cerl.gui.utilities.Class selectSurveyClass, StepThree parentStep) {
        this.parentStep = parentStep;
        
        /**
         * Creates a clean deep clone of the census classes. 
         * This will be used for when the user hits cancel.
         */
        parentStep.selectSurveyClass.getSurveyColumnValuesGroupings().stream().forEach((c) -> {
            try {
                this.nonEditedSurveyColumnValuesGroupings.add(c.clone());
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(CensusClassUserDefinitions.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        parentStep.selectSurveyClass.getAllSurveyColumnValuesNotUsed().stream().forEach((c) -> {
            try {
                this.nonEditedSurveyColumnValues.add(c.clone());
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(CensusClassUserDefinitions.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        
        this.selectSurveyClass = selectSurveyClass;
        this.surveyColumnGroupsTableItemModel = new SurveyColumnGroupsTableItemModel(this.selectSurveyClass.getSurveyColumnValuesGroupings());
        
        initComponents();
        allSurveyClassesList = new JList(this.selectSurveyClass.getAllSurveyColumnValuesNotUsed().toArray());
        
        jScrollPaneAllSurveyData.setViewportView(allSurveyClassesList);
        
        txtSelectedSurveyDataClass.setText(this.selectSurveyClass.getClassName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPaneAllSurveyData = new javax.swing.JScrollPane();
        btnAddNewCustomGrouping = new javax.swing.JButton();
        jLabel_SurveyColumns = new javax.swing.JLabel();
        jLabel_UserDescription = new javax.swing.JLabel();
        txtGroupingUserDefinedDescription = new javax.swing.JTextField();
        btnAddRestToNewGroups = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSelectedGroups = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel_SelectSurveyData = new javax.swing.JLabel();
        txtSelectedSurveyDataClass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAddNewCustomGrouping.setText("Add New Grouping");
        btnAddNewCustomGrouping.setToolTipText("");
        btnAddNewCustomGrouping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCustomGroupingActionPerformed(evt);
            }
        });

        jLabel_SurveyColumns.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_SurveyColumns.setText("Available Survey Data Column Values:");

        jLabel_UserDescription.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_UserDescription.setText("User Defined Description:");

        btnAddRestToNewGroups.setText("Rest of Values Are Individual Descriptions");
        btnAddRestToNewGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRestToNewGroupsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneAllSurveyData)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_UserDescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGroupingUserDefinedDescription))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_SurveyColumns, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddNewCustomGrouping, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddRestToNewGroups, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel_SurveyColumns, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneAllSurveyData, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_UserDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGroupingUserDefinedDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddNewCustomGrouping)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddRestToNewGroups)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableSelectedGroups.setModel(surveyColumnGroupsTableItemModel);
        jScrollPane1.setViewportView(jTableSelectedGroups);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_SelectSurveyData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_SelectSurveyData.setText("Select Survey Data:");

        txtSelectedSurveyDataClass.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_SelectSurveyData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSelectedSurveyDataClass)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_SelectSurveyData)
                    .addComponent(txtSelectedSurveyDataClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Group Survey Data Columns:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(12, 12, 12))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenuHelp.setText("Help");
        jMenuHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHelpMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuHelp);

        jMenuAbout.setText("About");
        jMenuAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the creation of a new custom grouping - creates a new custom group and adds it to the table
     * @param evt 
     */
    private void btnAddNewCustomGroupingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCustomGroupingActionPerformed
       
        ArrayList<SurveyColumnValue> selected = 
                (ArrayList<SurveyColumnValue>) allSurveyClassesList.getSelectedValuesList();
        
        SurveyColumnValuesGrouping newSurveyColumnValuesGrouping = 
                new SurveyColumnValuesGrouping(
                        txtGroupingUserDefinedDescription.getText(),
                        selected);
        
        this.selectSurveyClass.addSurveyGrouping(newSurveyColumnValuesGrouping);
        selected.stream().forEach((c) -> {c.setUsed(true);});

        allSurveyClassesList = new JList(selectSurveyClass.getAllSurveyColumnValuesNotUsed().toArray());
        jScrollPaneAllSurveyData.setViewportView(allSurveyClassesList);
        this.surveyColumnGroupsTableItemModel.fireTableDataChanged();
    }//GEN-LAST:event_btnAddNewCustomGroupingActionPerformed

    /**
     * Creates a new group for each of the remaining items, where each remaining item is it's own group
     * @param evt 
     */
    private void btnAddRestToNewGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRestToNewGroupsActionPerformed
        List<SurveyColumnValue> selected = selectSurveyClass.getAllSurveyColumnValuesNotUsed();
        
        selected.stream().forEach((c) -> {
            c.setUsed(true); 
            SurveyColumnValuesGrouping newSurveyColumnValuesGrouping = new SurveyColumnValuesGrouping();
            newSurveyColumnValuesGrouping.addToSurveyColumnValues(c);
            this.selectSurveyClass.addSurveyGrouping(newSurveyColumnValuesGrouping);
        });
        
        allSurveyClassesList = new JList(selectSurveyClass.getAllSurveyColumnValuesNotUsed().toArray());
        jScrollPaneAllSurveyData.setViewportView(allSurveyClassesList);
        this.surveyColumnGroupsTableItemModel.fireTableDataChanged();
    }//GEN-LAST:event_btnAddRestToNewGroupsActionPerformed

    /**
     * Saves the information provided
     * @param evt 
     */
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        List<SurveyColumnValue> allSurveyColumnValuesNotUsed = selectSurveyClass.getAllSurveyColumnValuesNotUsed();
        
        int leftUnGroupedCount = allSurveyColumnValuesNotUsed.size();
        if(leftUnGroupedCount == 0){
            this.parentStep.updateSurveyGroupsListModel();
            this.parentStep.setVisible(true);
            this.parentStep.setAlwaysOnTop(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(
                    this,
                    "All survey classes must be grouped.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * Cancels changes made to the page, and reverts to the last saved version
     * @param evt 
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.parentStep.selectSurveyClass.setSurveyColumnValuesGroupings(this.nonEditedSurveyColumnValuesGroupings);
        this.parentStep.selectSurveyClass.setAllSurveyColumnValues(this.nonEditedSurveyColumnValues);
        this.parentStep.setVisible(true);
        this.parentStep.setAlwaysOnTop(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * Closes the window, and goes back to the parent step
     * @param evt 
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.parentStep.selectSurveyClass.setSurveyColumnValuesGroupings(this.nonEditedSurveyColumnValuesGroupings);
        this.parentStep.selectSurveyClass.setAllSurveyColumnValues(this.nonEditedSurveyColumnValues);
        this.parentStep.setVisible(true);
        this.parentStep.setAlwaysOnTop(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * Handles the help menu item, displays the help information for the current screen
     * @param evt 
     */
    private void jMenuHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHelpMouseClicked
        DigPopGUIUtilityClass.loadDefaultHelpGUIByScreenName(SCREEN_NAME);
    }//GEN-LAST:event_jMenuHelpMouseClicked

    /**
     * Handles the about menu, opens the About pop-up
     * @param evt 
     */
    private void jMenuAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAboutMouseClicked
        new About().setVisible(true);
    }//GEN-LAST:event_jMenuAboutMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewCustomGrouping;
    private javax.swing.JButton btnAddRestToNewGroups;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_SelectSurveyData;
    private javax.swing.JLabel jLabel_SurveyColumns;
    private javax.swing.JLabel jLabel_UserDescription;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneAllSurveyData;
    private javax.swing.JTable jTableSelectedGroups;
    private javax.swing.JTextField txtGroupingUserDefinedDescription;
    private javax.swing.JTextField txtSelectedSurveyDataClass;
    // End of variables declaration//GEN-END:variables
}
