/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cerl.gui.forms;

/**
 *
 * @author ajohnson
 */
public class StepZero extends javax.swing.JFrame {
    
    /**
     * Ex: 08_26_2016_DigiPop_Run.xml
     */
    private final String DEFAULT_NEW_FILE_NAME = "DigiPop_Run.xml";
    private final String NEW_TAB_NAME = "New";
    private final String OPEN_TAB_NAME = "Open";
    private final String DUPLICATE_TAB_NAME = "Duplicate";

    /**
     * Creates new form StepZero
     */
    public StepZero() {
        initComponents();
        
        enableNewFileTab(false);
        enableOpenFileTab(false);
        enableDuplicateFileTab(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        buttonGroupSelectRun = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPanel = new javax.swing.JTabbedPane();
        tabbedPanelNew = new javax.swing.JPanel();
        lblNewFileName = new javax.swing.JLabel();
        lblNewFileLocation = new javax.swing.JLabel();
        btnSelectNewFileLocation = new javax.swing.JButton();
        txtNewFileName = new javax.swing.JTextField();
        txtNewFileLocation = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnNew = new javax.swing.JRadioButton();
        btnOpen = new javax.swing.JRadioButton();
        btnDuplicate = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\"));
            jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText("Welcome to the DigiPop GUI");

            jTabbedPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            tabbedPanelNew.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            lblNewFileName.setText("New File Name:");

            lblNewFileLocation.setText("File Location:");

            btnSelectNewFileLocation.setText("Select Location");
            btnSelectNewFileLocation.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSelectNewFileLocationActionPerformed(evt);
                }
            });

            txtNewFileLocation.setEditable(false);

            javax.swing.GroupLayout tabbedPanelNewLayout = new javax.swing.GroupLayout(tabbedPanelNew);
            tabbedPanelNew.setLayout(tabbedPanelNewLayout);
            tabbedPanelNewLayout.setHorizontalGroup(
                tabbedPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabbedPanelNewLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(tabbedPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabbedPanelNewLayout.createSequentialGroup()
                            .addComponent(lblNewFileName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNewFileName))
                        .addGroup(tabbedPanelNewLayout.createSequentialGroup()
                            .addComponent(lblNewFileLocation)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNewFileLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSelectNewFileLocation)))
                    .addContainerGap())
            );
            tabbedPanelNewLayout.setVerticalGroup(
                tabbedPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tabbedPanelNewLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(tabbedPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNewFileName)
                        .addComponent(txtNewFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(tabbedPanelNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNewFileLocation)
                        .addComponent(btnSelectNewFileLocation)
                        .addComponent(txtNewFileLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(21, Short.MAX_VALUE))
            );

            jTabbedPanel.addTab("New", tabbedPanelNew);

            jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 517, Short.MAX_VALUE)
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 86, Short.MAX_VALUE)
            );

            jTabbedPanel.addTab("Open", jPanel3);

            jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 517, Short.MAX_VALUE)
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 86, Short.MAX_VALUE)
            );

            jTabbedPanel.addTab("Duplicate", jPanel4);

            jButton2.setText("Next");
            jButton2.setEnabled(false);
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            buttonGroupSelectRun.add(btnNew);
            btnNew.setText("New");
            btnNew.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnNewActionPerformed(evt);
                }
            });

            buttonGroupSelectRun.add(btnOpen);
            btnOpen.setText("Open");
            btnOpen.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnOpenActionPerformed(evt);
                }
            });

            buttonGroupSelectRun.add(btnDuplicate);
            btnDuplicate.setText("Duplicate");
            btnDuplicate.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnDuplicateActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTabbedPanel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnNew)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnOpen)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnDuplicate)
                                    .addGap(185, 185, 185)))))
                    .addGap(10, 10, 10))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNew)
                        .addComponent(btnOpen)
                        .addComponent(btnDuplicate))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton2)
                    .addContainerGap())
            );

            jMenu1.setText("File");
            jMenuBar1.add(jMenu1);

            jMenu2.setText("Edit");
            jMenuBar1.add(jMenu2);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnSelectNewFileLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectNewFileLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSelectNewFileLocationActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        if(btnNew.isSelected())
        {
            enableNewFileTab(true);
            enableOpenFileTab(false);
            enableDuplicateFileTab(false);
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        if(btnOpen.isSelected())
        {
            enableNewFileTab(false);
            enableOpenFileTab(true);
            enableDuplicateFileTab(false);
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnDuplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuplicateActionPerformed
        if(btnDuplicate.isSelected())
        {
            enableNewFileTab(false);
            enableOpenFileTab(false);
            enableDuplicateFileTab(true);
        }
    }//GEN-LAST:event_btnDuplicateActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StepZero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StepZero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StepZero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StepZero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StepZero().setVisible(true);
            }
        });
    }
    
    private void enableNewFileTab(Boolean enable){
        txtNewFileName.setEnabled(enable);
        txtNewFileLocation.setEnabled(enable);
        btnSelectNewFileLocation.setEnabled(enable);
        lblNewFileName.setEnabled(enable);
        lblNewFileLocation.setEnabled(enable);
        
        int index = jTabbedPanel.indexOfTab(
                            NEW_TAB_NAME);
        
        jTabbedPanel.setEnabledAt(
                    index, 
                    enable);
        
        if(enable){
            jTabbedPanel.setSelectedIndex(index);
        }
    }
    
    private void enableOpenFileTab(Boolean enable){
        int index = jTabbedPanel.indexOfTab(
                            OPEN_TAB_NAME);
        
        jTabbedPanel.setEnabledAt(
                    index, 
                    enable);
        
        if(enable){
            jTabbedPanel.setSelectedIndex(index);
        }
    }
    
    private void enableDuplicateFileTab(Boolean enable){
        int index = jTabbedPanel.indexOfTab(
                            DUPLICATE_TAB_NAME);
        
        jTabbedPanel.setEnabledAt(
                    index, 
                    enable);
        
        if(enable){
            jTabbedPanel.setSelectedIndex(index);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnDuplicate;
    private javax.swing.JRadioButton btnNew;
    private javax.swing.JRadioButton btnOpen;
    private javax.swing.JButton btnSelectNewFileLocation;
    private javax.swing.ButtonGroup buttonGroupSelectRun;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPanel;
    private javax.swing.JLabel lblNewFileLocation;
    private javax.swing.JLabel lblNewFileName;
    private javax.swing.JPanel tabbedPanelNew;
    private javax.swing.JTextField txtNewFileLocation;
    private javax.swing.JTextField txtNewFileName;
    // End of variables declaration//GEN-END:variables
}
