/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cerl.gui.forms;

import cerl.gui.standard.utilities.Result;
import cerl.gui.utilities.DigPopGUIInformation;
import cerl.gui.utilities.DigPopGUIUtilityClass;
import cerl.gui.utilities.HelpFileScreenNames;
import cerl.gui.utilities.LandUseCombinationTableItemModel;
import cerl.gui.utilities.VacantClass;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajohnson
 */
public class StepTwo extends javax.swing.JFrame {
    
    private DefaultTableModel constraintMapsDataModel;
    private ArrayList<String> errors;
    private final String SCREEN_NAME = HelpFileScreenNames.STEP_TWO_HELP_FILE_NAME.toString();
    private LandUseCombinationTableItemModel landUseCombinationTableItemModel;
    private final DigPopGUIInformation digPopGUIInformation;
    
    private Result landUseLoadClassesResult = new Result();

    /**
     * Creates new form StepOne
     */
    public StepTwo() {
        this.digPopGUIInformation = new DigPopGUIInformation();
        this.landUseCombinationTableItemModel = new LandUseCombinationTableItemModel(this.digPopGUIInformation.getLandUseMapInformation().getLandUseMapClassCombinations());
        initComponents();
        
        errors = new ArrayList<String>();
        pack();
    }
    
    /**
     * Creates new form StepOne
     */
    public StepTwo(DigPopGUIInformation digPopGUIInformation) {
        this.digPopGUIInformation = digPopGUIInformation;
        this.landUseCombinationTableItemModel = new LandUseCombinationTableItemModel(this.digPopGUIInformation.getLandUseMapInformation().getLandUseMapClassCombinations());
        
        initComponents();
        errors = new ArrayList<String>();
        populateDataFieldsFromFile();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogLoadingFile = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanelStepTwo = new javax.swing.JPanel();
        jPanelRegionMapCensusEnum = new javax.swing.JPanel();
        txtRegionMap = new javax.swing.JTextField();
        txtCensusEnumerations = new javax.swing.JTextField();
        lblRegionMap = new javax.swing.JLabel();
        lblCensusEnumerations = new javax.swing.JLabel();
        jPanelHouseholdDensityMap = new javax.swing.JPanel();
        txtHouseholdDensityMap = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanelHouseholdMicroData = new javax.swing.JPanel();
        txtHouseholdMicroData = new javax.swing.JTextField();
        lblHouseholdMicroData = new javax.swing.JLabel();
        jPanelPopulationMicroData = new javax.swing.JPanel();
        txtPopulationMicroData = new javax.swing.JTextField();
        lblPopulationMicroData = new javax.swing.JLabel();
        jPanelLandUseHouseholdMap = new javax.swing.JPanel();
        lblConstraintMap = new javax.swing.JLabel();
        txtLandUseHouseholdMap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtVacantClasses = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtVacantClassDescription = new javax.swing.JTextField();
        btnLandUseAddCombinationClass = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLandUseClassCombinations = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtLandUseComment = new javax.swing.JTextField();
        jPanelConstraintMap = new javax.swing.JPanel();
        lblConstraintMap1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConstraintMaps1 = new javax.swing.JTable();
        btnPreviousStep = new javax.swing.JButton();
        lblErrorMessages = new javax.swing.JLabel();
        btnNextStep = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemExitApplication = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        jMenu_About = new javax.swing.JMenu();

        jDialogLoadingFile.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jDialogLoadingFile.setAlwaysOnTop(true);
        jDialogLoadingFile.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jDialogLoadingFile.setModal(true);
        jDialogLoadingFile.setResizable(false);
        jDialogLoadingFile.setType(java.awt.Window.Type.UTILITY);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Please Wait While File is Loading.....");

        jProgressBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jProgressBar1.setIndeterminate(true);
        jProgressBar1.setString("");

        javax.swing.GroupLayout jDialogLoadingFileLayout = new javax.swing.GroupLayout(jDialogLoadingFile.getContentPane());
        jDialogLoadingFile.getContentPane().setLayout(jDialogLoadingFileLayout);
        jDialogLoadingFileLayout.setHorizontalGroup(
            jDialogLoadingFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogLoadingFileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogLoadingFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialogLoadingFileLayout.setVerticalGroup(
            jDialogLoadingFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogLoadingFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Step Two");

        jPanelStepTwo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelRegionMapCensusEnum.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtRegionMap.setEditable(false);

        txtCensusEnumerations.setEditable(false);

        lblRegionMap.setText("Selected Region Map:");

        lblCensusEnumerations.setText("Selected Census Enumerations:");

        javax.swing.GroupLayout jPanelRegionMapCensusEnumLayout = new javax.swing.GroupLayout(jPanelRegionMapCensusEnum);
        jPanelRegionMapCensusEnum.setLayout(jPanelRegionMapCensusEnumLayout);
        jPanelRegionMapCensusEnumLayout.setHorizontalGroup(
            jPanelRegionMapCensusEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegionMapCensusEnumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegionMapCensusEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegionMapCensusEnumLayout.createSequentialGroup()
                        .addComponent(lblCensusEnumerations)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCensusEnumerations))
                    .addGroup(jPanelRegionMapCensusEnumLayout.createSequentialGroup()
                        .addComponent(lblRegionMap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRegionMap)))
                .addContainerGap())
        );
        jPanelRegionMapCensusEnumLayout.setVerticalGroup(
            jPanelRegionMapCensusEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegionMapCensusEnumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegionMapCensusEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegionMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegionMap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegionMapCensusEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCensusEnumerations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCensusEnumerations))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanelHouseholdDensityMap.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtHouseholdDensityMap.setEditable(false);

        jLabel1.setText("Selected Household Density Map:");

        javax.swing.GroupLayout jPanelHouseholdDensityMapLayout = new javax.swing.GroupLayout(jPanelHouseholdDensityMap);
        jPanelHouseholdDensityMap.setLayout(jPanelHouseholdDensityMapLayout);
        jPanelHouseholdDensityMapLayout.setHorizontalGroup(
            jPanelHouseholdDensityMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHouseholdDensityMapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHouseholdDensityMap, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelHouseholdDensityMapLayout.setVerticalGroup(
            jPanelHouseholdDensityMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHouseholdDensityMapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHouseholdDensityMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHouseholdDensityMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelHouseholdMicroData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelHouseholdMicroData.setMinimumSize(new java.awt.Dimension(100, 100));

        txtHouseholdMicroData.setEditable(false);

        lblHouseholdMicroData.setText("Selected Household Micro-data:");

        javax.swing.GroupLayout jPanelHouseholdMicroDataLayout = new javax.swing.GroupLayout(jPanelHouseholdMicroData);
        jPanelHouseholdMicroData.setLayout(jPanelHouseholdMicroDataLayout);
        jPanelHouseholdMicroDataLayout.setHorizontalGroup(
            jPanelHouseholdMicroDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHouseholdMicroDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHouseholdMicroData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHouseholdMicroData)
                .addContainerGap())
        );
        jPanelHouseholdMicroDataLayout.setVerticalGroup(
            jPanelHouseholdMicroDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHouseholdMicroDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHouseholdMicroDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHouseholdMicroData)
                    .addComponent(txtHouseholdMicroData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPopulationMicroData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPopulationMicroData.setMinimumSize(new java.awt.Dimension(100, 100));

        txtPopulationMicroData.setEditable(false);

        lblPopulationMicroData.setText("Selected Population Micro-data:");

        javax.swing.GroupLayout jPanelPopulationMicroDataLayout = new javax.swing.GroupLayout(jPanelPopulationMicroData);
        jPanelPopulationMicroData.setLayout(jPanelPopulationMicroDataLayout);
        jPanelPopulationMicroDataLayout.setHorizontalGroup(
            jPanelPopulationMicroDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPopulationMicroDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPopulationMicroData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPopulationMicroData)
                .addContainerGap())
        );
        jPanelPopulationMicroDataLayout.setVerticalGroup(
            jPanelPopulationMicroDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPopulationMicroDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPopulationMicroDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopulationMicroData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPopulationMicroData))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelLandUseHouseholdMap.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelLandUseHouseholdMap.setMinimumSize(new java.awt.Dimension(100, 100));

        lblConstraintMap.setText("Selected Land Use Map:");

        txtLandUseHouseholdMap.setEditable(false);

        jLabel2.setText("Vacant Classes: ");

        jLabel3.setText("Vacant Class Description: ");

        btnLandUseAddCombinationClass.setText("Add Custom Combination of Classes");
        btnLandUseAddCombinationClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLandUseAddCombinationClassActionPerformed(evt);
            }
        });

        jTableLandUseClassCombinations.setModel(landUseCombinationTableItemModel);
        jScrollPane1.setViewportView(jTableLandUseClassCombinations);

        jLabel4.setText("Comment: ");

        javax.swing.GroupLayout jPanelLandUseHouseholdMapLayout = new javax.swing.GroupLayout(jPanelLandUseHouseholdMap);
        jPanelLandUseHouseholdMap.setLayout(jPanelLandUseHouseholdMapLayout);
        jPanelLandUseHouseholdMapLayout.setHorizontalGroup(
            jPanelLandUseHouseholdMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLandUseHouseholdMapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLandUseHouseholdMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addGroup(jPanelLandUseHouseholdMapLayout.createSequentialGroup()
                        .addComponent(lblConstraintMap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLandUseHouseholdMap))
                    .addGroup(jPanelLandUseHouseholdMapLayout.createSequentialGroup()
                        .addComponent(btnLandUseAddCombinationClass)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelLandUseHouseholdMapLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanelLandUseHouseholdMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLandUseHouseholdMapLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVacantClassDescription))
                            .addGroup(jPanelLandUseHouseholdMapLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVacantClasses))
                            .addGroup(jPanelLandUseHouseholdMapLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLandUseComment)))))
                .addContainerGap())
        );
        jPanelLandUseHouseholdMapLayout.setVerticalGroup(
            jPanelLandUseHouseholdMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLandUseHouseholdMapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLandUseHouseholdMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConstraintMap)
                    .addComponent(txtLandUseHouseholdMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLandUseHouseholdMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLandUseComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLandUseHouseholdMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVacantClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLandUseHouseholdMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtVacantClassDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLandUseAddCombinationClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelConstraintMap.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelConstraintMap.setMinimumSize(new java.awt.Dimension(100, 100));

        lblConstraintMap1.setText("Selected Constraint Maps :");

        tblConstraintMaps1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File Path"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblConstraintMaps1);

        javax.swing.GroupLayout jPanelConstraintMapLayout = new javax.swing.GroupLayout(jPanelConstraintMap);
        jPanelConstraintMap.setLayout(jPanelConstraintMapLayout);
        jPanelConstraintMapLayout.setHorizontalGroup(
            jPanelConstraintMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConstraintMapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConstraintMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addGroup(jPanelConstraintMapLayout.createSequentialGroup()
                        .addComponent(lblConstraintMap1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelConstraintMapLayout.setVerticalGroup(
            jPanelConstraintMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConstraintMapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConstraintMap1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelStepTwoLayout = new javax.swing.GroupLayout(jPanelStepTwo);
        jPanelStepTwo.setLayout(jPanelStepTwoLayout);
        jPanelStepTwoLayout.setHorizontalGroup(
            jPanelStepTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStepTwoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStepTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHouseholdDensityMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPopulationMicroData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRegionMapCensusEnum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelHouseholdMicroData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelLandUseHouseholdMap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelStepTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelStepTwoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelConstraintMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelStepTwoLayout.setVerticalGroup(
            jPanelStepTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStepTwoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRegionMapCensusEnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPopulationMicroData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHouseholdMicroData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHouseholdDensityMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelLandUseHouseholdMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(jPanelStepTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStepTwoLayout.createSequentialGroup()
                    .addContainerGap(452, Short.MAX_VALUE)
                    .addComponent(jPanelConstraintMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(1, 1, 1)))
        );

        btnPreviousStep.setText("Previous Step");
        btnPreviousStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousStepActionPerformed(evt);
            }
        });

        lblErrorMessages.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblErrorMessages.setForeground(new java.awt.Color(255, 0, 0));

        btnNextStep.setText("Next Step");
        btnNextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextStepActionPerformed(evt);
            }
        });

        menuFile.setText("File");

        menuItemExitApplication.setText("Exit Application");
        menuFile.add(menuItemExitApplication);

        jMenuBar.add(menuFile);

        menuHelp.setText("Help");
        menuHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHelpMouseClicked(evt);
            }
        });
        jMenuBar.add(menuHelp);

        jMenu_About.setText("About");
        jMenu_About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_AboutMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenu_About);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPreviousStep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNextStep))
                    .addComponent(jPanelStepTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorMessages)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelStepTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPreviousStep)
                    .addComponent(btnNextStep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorMessages))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_AboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_AboutMouseClicked
        new About().setVisible(true);
    }//GEN-LAST:event_jMenu_AboutMouseClicked

    private void menuHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHelpMouseClicked
        DigPopGUIUtilityClass.loadDefaultHelpGUIByScreenName(SCREEN_NAME);
    }//GEN-LAST:event_menuHelpMouseClicked

    private void btnPreviousStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousStepActionPerformed
        save();
        
        new StepOne(this.digPopGUIInformation).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPreviousStepActionPerformed

    private void btnNextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextStepActionPerformed
        save();
        
        new StepThree(this.digPopGUIInformation).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNextStepActionPerformed

    private void btnLandUseAddCombinationClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLandUseAddCombinationClassActionPerformed

        if(this.digPopGUIInformation.getLandUseMapInformation().getAllClasses() == null
                || this.digPopGUIInformation.getLandUseMapInformation().getAllClasses().size() == 0 ){
            SwingWorker<Void,Void> worker = new SwingWorker<Void,Void>()
            {
                @Override
                protected Void doInBackground()
                {
                    DateFormat df = new SimpleDateFormat("dd/MM/yy HH:mm:ss");
                    Date dateobj = new Date();
                    System.out.println(df.format(dateobj));
                    try {
                        landUseLoadClassesResult = DigPopGUIUtilityClass.getClassesFromLandUseASCFile(digPopGUIInformation.getLandUseMapFilePath());
                    } catch (IOException ex) {
                        landUseLoadClassesResult.setErrorMessage("DigPopGUIUtilityClass.getClassesFromLandUseASCFile", ex.getMessage());
                        landUseLoadClassesResult.setSuccess(false);
                    }

                    dateobj = new Date();
                    System.out.println(df.format(dateobj));
                    return null;
                }

                @Override
                protected void done()
                {
                    if(landUseLoadClassesResult.isSuccess()){
                        ArrayList<String> classes = (ArrayList<String>)landUseLoadClassesResult.getValue();

                        digPopGUIInformation.getLandUseMapInformation().setAllClasses(classes);
                    }
                    jDialogLoadingFile.dispose();
                }
            };

            worker.execute();

            jDialogLoadingFile.pack();
            jDialogLoadingFile.setLocationRelativeTo(this);
            jDialogLoadingFile.setVisible(true);
        }
        else
        {
            landUseLoadClassesResult.setSuccess(true);
        }

        if(landUseLoadClassesResult.isSuccess()){
            LandUseDefineCombinationClasses landUseDefineCombinationClasses = new LandUseDefineCombinationClasses(this.digPopGUIInformation, this);
            landUseDefineCombinationClasses.setVisible(true);
            landUseDefineCombinationClasses.setAlwaysOnTop(true);
            landUseDefineCombinationClasses.setLocationRelativeTo(this);
            this.setVisible(false);
            this.setAlwaysOnTop(false);
        }

        landUseLoadClassesResult = new Result();
    }//GEN-LAST:event_btnLandUseAddCombinationClassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StepTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StepTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StepTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StepTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StepTwo().setVisible(true);
            }
        });
    }
    
    private void AddItemToConstaintMapTable(String value){
        DefaultTableModel model = (DefaultTableModel)tblConstraintMaps1.getModel();
        Object[] obj = {value};
        model.addRow(obj);
    }
    
    private void setErrorMessage()
    {
        String errorMessageText = "<html>";
        
        for(String error : errors)
        {
            if(errorMessageText.length()>6)
            {
                errorMessageText = String.format(
                        "%s<br>%s", 
                        errorMessageText, 
                        error);
            }else{
                errorMessageText = errorMessageText + error;
            }
        }
        
        lblErrorMessages.setText(errorMessageText);
        ((JFrame)lblErrorMessages.getTopLevelAncestor()).pack();
    }
    
    /**
     * Populates the text fields from an existing save file
     */
    private void populateDataFieldsFromFile(){
        if(this.digPopGUIInformation == null){
            return;
        }
        
        if((this.digPopGUIInformation.getLandUseMapFilePath() != null) && !this.digPopGUIInformation.getLandUseMapFilePath().equals("")){
            txtLandUseHouseholdMap.setText(this.digPopGUIInformation.getLandUseMapFilePath());
            jPanelLandUseHouseholdMap.setVisible(true);
            jPanelHouseholdDensityMap.setVisible(false);
            
            UpdateLandUseClassCombinationTable();
            if((this.digPopGUIInformation.getLandUseMapInformation() != null) 
                    && (this.digPopGUIInformation.getLandUseMapInformation().getVacantClasses() != null))
            {
                this.txtVacantClassDescription.setText(this.digPopGUIInformation.getLandUseMapInformation().getVacantClasses().getDescription());
                this.txtVacantClasses.setText(this.digPopGUIInformation.getLandUseMapInformation().getVacantClasses().getClasses());
            }
            this.txtLandUseComment.setText(this.digPopGUIInformation.getLandUseMapInformation().getComment());
            
        } else{
            txtHouseholdDensityMap.setText(this.digPopGUIInformation.getHouseholdDensityMapFilePath());
            jPanelLandUseHouseholdMap.setVisible(false);
            jPanelHouseholdDensityMap.setVisible(true);
        }
        
        txtRegionMap.setText(this.digPopGUIInformation.getRegionMapFilePath());
        txtCensusEnumerations.setText(this.digPopGUIInformation.getCensusEnumerationsFilePath());
        
        if(this.digPopGUIInformation.getConstraintMapsFilePaths() != null){
            for(int i = 0; i<this.digPopGUIInformation.getConstraintMapsFilePaths().size(); i++){
                AddItemToConstaintMapTable(this.digPopGUIInformation.getConstraintMapsFilePaths().get(i));
            }
        }

        txtPopulationMicroData.setText(this.digPopGUIInformation.getPopulationMicroDataFilePath());
        txtHouseholdMicroData.setText(this.digPopGUIInformation.getHouseholdMicroDataFilePath());
        
        pack();
    }
    
    public void UpdateLandUseClassCombinationTable(){
        if(this.digPopGUIInformation.getLandUseMapInformation().getLandUseMapClassCombinations().size()>0){
            this.landUseCombinationTableItemModel.fireTableDataChanged();
            pack();
        }
    }
    
    private void save(){
        VacantClass vacant = new VacantClass(this.txtVacantClassDescription.getText(), this.txtVacantClasses.getText());
        this.digPopGUIInformation.getLandUseMapInformation().setVacantClasses(vacant);
        this.digPopGUIInformation.getLandUseMapInformation().setComment(this.txtLandUseComment.getText());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLandUseAddCombinationClass;
    private javax.swing.JButton btnNextStep;
    private javax.swing.JButton btnPreviousStep;
    private javax.swing.JDialog jDialogLoadingFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenu_About;
    private javax.swing.JPanel jPanelConstraintMap;
    private javax.swing.JPanel jPanelHouseholdDensityMap;
    private javax.swing.JPanel jPanelHouseholdMicroData;
    private javax.swing.JPanel jPanelLandUseHouseholdMap;
    private javax.swing.JPanel jPanelPopulationMicroData;
    private javax.swing.JPanel jPanelRegionMapCensusEnum;
    private javax.swing.JPanel jPanelStepTwo;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableLandUseClassCombinations;
    private javax.swing.JLabel lblCensusEnumerations;
    private javax.swing.JLabel lblConstraintMap;
    private javax.swing.JLabel lblConstraintMap1;
    private javax.swing.JLabel lblErrorMessages;
    private javax.swing.JLabel lblHouseholdMicroData;
    private javax.swing.JLabel lblPopulationMicroData;
    private javax.swing.JLabel lblRegionMap;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemExitApplication;
    private javax.swing.JTable tblConstraintMaps1;
    private javax.swing.JTextField txtCensusEnumerations;
    private javax.swing.JTextField txtHouseholdDensityMap;
    private javax.swing.JTextField txtHouseholdMicroData;
    private javax.swing.JTextField txtLandUseComment;
    private javax.swing.JTextField txtLandUseHouseholdMap;
    private javax.swing.JTextField txtPopulationMicroData;
    private javax.swing.JTextField txtRegionMap;
    private javax.swing.JTextField txtVacantClassDescription;
    private javax.swing.JTextField txtVacantClasses;
    // End of variables declaration//GEN-END:variables
}
